[phases.setup]
nixPkgs = ["nodejs_22", "gcc", "gnumake"]

[phases.install]
cmds = [
  "npm --prefix frontend install --include=dev"
]

[phases.build]
cmds = [
  "npm --prefix frontend run build",
  "make --directory cpp"
]

[start]
cmd = "node backend/server.js"
